# Generated by Django 5.2.13 on 2026-04-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='calculated_host_listings_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
