# Generated by Django 5.2.13 on 2026-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_host_calculated_host_listings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host_id', models.IntegerField()),
                ('neighbourhood_group', models.CharField(max_length=100)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('minimum_nights', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('last_review', models.DateField(blank=True, null=True)),
                ('reviews_per_month', models.FloatField(blank=True, null=True)),
                ('availability_365', models.IntegerField()),
                ('number_of_reviews_ltm', models.IntegerField()),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.FloatField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
