# Generated by Django 5.2.13 on 2026-05-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listing_delete_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='calculated_host_listings_count',
            new_name='listings_count',
        ),
    ]
