# Generated by Django 5.2.13 on 2026-05-01 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_calculated_host_listings_count_host_listings_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host'),
        ),
    ]
